services:
  mysql:
    image: mysql:8.3.0
    container_name: mysqli
    environment:
      MYSQL_ROOT_PASSWORD: Aaana1234!
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql:/data:/var/lib/mysql